### ISSUE TITLE
Display additional book details

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v24-geckos-team-02#5]
**User Story Description**
As a End User
I want to click on a book to display additional details
So I can view additional details to help me decide if I want to read it

**Steps to Follow (optional)**
- [ ] Identify additional book details that should be displayed in the search results or when the user clicks on a book in that list
- [ ] Additional steps as necessary

**Additional Considerations**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by Guitarhub786** [comment]
"So I can view additional details to help me decide if I want to read it"
Maybe also: Or buy it.

**Comment by jdmedlock** [comment]
In response to your question in the Team Channel here are my thoughts. Others please add your's if I've missed something or if you disagree.

The result of a user's search will be a list of books that match the search criteria. To keep this list concise the entries for the books will contain summary information. If the user want's more information about a book she would click on it in the search results to display more details. 

The goal of this task is to identify what those additional details are and to implement the UI to handle the click and display a dialog or page showing them all for the book. 

A design decision you'll have to make is which is best. another page or a dialog or something else? Since @willnwhite has been working on the search function you'll probably need to collaborate with him on this and with @snrelghgub on UI/UX considerations.

**Comment by snrelghgub** [comment]
Hi @mokokom, additional details to find out whether a book is free or not I think is worth investigating. Another suggestion I can think of is to provide a fuller description of the book that the User is interested in reading without having to leave the landing page. I would also be interested to hear your suggestions; perhaps you have different ones to mine?

**Comment by mokokom** [comment]
thank you for your suggestions. I will implement the details of whether or not a book is free as you suggest. About the display, I will use a modal or drop down (depending on the general layout of the cardslist) so that the user doesn't leave the page when he asks for more details. For the rest I indicated the description of the book, year of publication, link to an overview, a link to the purchase, and a link to the book's info on google play. Any other suggestion is welcome. About the frontend part I'll suggest to do it after the PR is reviewed and approved (for now there is no style at all) so that I will have acces to @snrelghgub css class implementation. Does it seems to be a good workflow?

**Comment by mokokom** [comment]
Unless I'm mistaken, I think that the information about free access to a book is only available with an API key.
